[env:esp32dev]
platform = espressif32
board = esp32-devkitc-v4
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    https://github.com/playfultechnology/esp32-eyes.git
build_flags =
    -DDEBUG=1

[env:esp32dev-release]
platform = espressif32
board = esp32-devkitc-v4
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    https://github.com/playfultechnology/esp32-eyes.git
build_flags =
    -DDEBUG=0
    -O2

; Wokwi simulation
[env:wokwi]
platform = espressif32
board = esp32-devkitc-v4
framework = arduino
test_framework = googletest
