[wokwi]
version = 1

[env]
WOKWI = 1

[[parts]]
type = "wokwi-esp32-devkit-v1"
id = "esp"
top = 0
left = 0

[[parts]]
type = "wokwi-ssd1306"
id = "oled"
top = 200
left = 0
attrs = { width = "128", height = "64" }

[[connections]]
from = "esp TX"
to = "OLED GND"

[[connections]]
from = "esp IO21"
to = "OLED SDA"

[[connections]]
from = "esp IO22"
to = "OLED SCL"
